EMPTY = None

#
# ------------ SOLVABLE ----------------
#
BOARD1= [
    [5, 3, EMPTY, EMPTY, 7, EMPTY, EMPTY, EMPTY, EMPTY],
    [6, EMPTY, EMPTY, 1, 9, 5, EMPTY, EMPTY, EMPTY],
    [EMPTY, 9, 8, EMPTY, EMPTY, EMPTY, EMPTY, 6, EMPTY],
    [8, EMPTY, EMPTY, EMPTY, 6, EMPTY, EMPTY, EMPTY, 3],
    [4, EMPTY, EMPTY, 8, EMPTY, 3, EMPTY, EMPTY, 1],
    [7, EMPTY, EMPTY, EMPTY, 2, EMPTY, EMPTY, EMPTY, 6],
    [EMPTY, 6, EMPTY, EMPTY, EMPTY, EMPTY, 2, 8, EMPTY],
    [EMPTY, EMPTY, EMPTY, 4, 1, 9, EMPTY, EMPTY, 5],
    [EMPTY, EMPTY, EMPTY, EMPTY, 8, EMPTY, EMPTY, 7, 9]
]

BOARD2 = [
    [EMPTY, EMPTY, EMPTY, EMPTY, 7, EMPTY, EMPTY, EMPTY, 9],
    [1, EMPTY, EMPTY, 4, EMPTY, EMPTY, EMPTY, 3, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, 3, 2, EMPTY, EMPTY],
    [EMPTY, 6, EMPTY, 2, EMPTY, EMPTY, EMPTY, 8, EMPTY],
    [EMPTY, EMPTY, 4, EMPTY, EMPTY, EMPTY, 7, EMPTY, EMPTY],
    [EMPTY, 8, EMPTY, EMPTY, EMPTY, 9, EMPTY, 6, EMPTY],
    [EMPTY, EMPTY, 1, 6, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, 9, EMPTY, EMPTY, EMPTY, 4, EMPTY, EMPTY, 1],
    [3, EMPTY, EMPTY, EMPTY, 9, EMPTY, EMPTY, EMPTY, EMPTY]
]

#
# ------------ UNSOLVABLE ----------------
#

BOARD3 = [
    [5, 5, EMPTY, EMPTY, 7, EMPTY, EMPTY, EMPTY, EMPTY],
    [6, EMPTY, EMPTY, 1, 9, 5, EMPTY, EMPTY, EMPTY],
    [EMPTY, 9, 8, EMPTY, EMPTY, EMPTY, EMPTY, 6, EMPTY],
    [8, EMPTY, EMPTY, EMPTY, 6, EMPTY, EMPTY, EMPTY, 3],
    [4, EMPTY, EMPTY, 8, EMPTY, 3, EMPTY, EMPTY, 1],
    [7, EMPTY, EMPTY, EMPTY, 2, EMPTY, EMPTY, EMPTY, 6],
    [EMPTY, 6, EMPTY, EMPTY, EMPTY, EMPTY, 2, 8, EMPTY],
    [EMPTY, EMPTY, EMPTY, 4, 1, 9, EMPTY, EMPTY, 5],
    [EMPTY, EMPTY, EMPTY, EMPTY, 8, EMPTY, EMPTY, 7, 9]
]

BOARD4 = [
    [5, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [5, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY]
]

ALL_BOARDS = [BOARD1,BOARD2,BOARD3,BOARD4]